### ISSUE TITLE
Add error handling and cleanup VerificationTable.jsx

### ISSUE THREAD

**Issue by samallari** [Team-Half-and-Half/spirebooks#102]
Please do work for this task in a branch called issue-102.

VerificationTable.jsx replace useTracker with withTracker, implement error handling with Meteor.call function, and increase column size (e.g. md{7}).

**Comment by beydlern** [comment]
The `useTracker` is a more optimized version of `withTracker` in this case because I am dealing with functional components rather than class components. Thus, I will not be replacing `useTracker` with `withTracker`.
