### ISSUE TITLE
Reorganize and Cleanup ManageDatabase Page

### ISSUE THREAD

**Issue by bksnelson** [Team-Half-and-Half/spirebooks#103]
Please do work for this task in a branch called issue-103.

- Separate functionality into its own component. Keep page and import component. 
- Move databaseFIleDateFromat into settings.development.json.
- Add comments to describe functionality and page. 
- Cleanup.

**Comment by beydlern** [comment]
ESLINT errors when pushing to main, fixing in the next commit.
