### ISSUE TITLE
Review 8: BudgetPLCollection.js and  Footer.jsx

### ISSUE THREAD

**Issue by bksnelson** [Team-Half-and-Half/spirebooks#142]
## Overview

Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-8

## Files to review

* [BudgetPLCollection.js](https://github.com/Team-Half-and-Half/spirebooks/blob/main/app/imports/api/spreadsheet/BudgetPLCollection.js)
* [Footer.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/main/app/imports/ui/components/Footer.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 11/4/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by t-tirabassi** [comment]
**BudgetPLCollection.js:**

JS-03: The spread operator can be used for updateData on line 48 instead of using the const.

JS-05: Arrow functions can be used for subscribeBudgetPL on line 93 and subscribeBudgetPLAdmin on line 104.

**Footer.jsx:**

Design-01/08: The different sections of the footer could be refactored into a separate const and then just mapped for each column in Footer to avoid repetition.

REACT-01: On top of refactoring, the column layout and props could be set up in a subcomponent and then just called into the Footer component.

**Comment by beydlern** [comment]
**BudgetPLCollection.js**

The `define`, `update`, and `removeIt` functions should incorporate error handling.

**Footer.jsx**

Each column section of the footer element contains duplicated code, the hyperlink tags and the line break tags, that should be restructured.

**Comment by caspascual** [comment]
BudgetPLCollection.js

L145: REACT-03: Should this instead be a default export with the same name?

Footer.jsx

ESLINT-02: Should add an ID for future TestCafe

**Comment by PaytonHAH** [comment]
### BudgetPLCollection.js

1. JS-05: Use arrow functions when appropriate. Functions in this file can be converted to arrow functions.

### Footer.jsx

1. TestCafe ID's Required
2. Design-08: Ensure code is DRY, some duplication with the columns.

**Comment by jsapolu99** [comment]
BudgetPLCollection.js: 
Use arrow functions where appropriate, such as in subscribeBudgetPL and subscribeBudgetPLAdmin, and consider adding error handling to define, update, and removeIt for better robustness.

Footer.jsx: 
Refactor repeated column elements into a separate constant and map them to each footer column to enhance readability and keep the code DRY.

**Comment by samallari** [comment]
BudgetPLCollection.js:
- add error handling for define, update, and remove for invalid inputs
- export const should have the same name as class
Footer.jsx:
- ensure code is DRY, consider refactoring repetitive code

**Comment by bksnelson** [comment]
BudgetPLCollection.js
Publication method could be split based on role. More roles will be added, making the method larger than needed.
But would require changing base collection.

Footer.jsx
Some additional padding on y axis could be added for container. L12

**Comment by samallari** [comment]
### Overview of Review Meeting
New Issues:
- Implement Error Handling for `define`, `update` and `removeIt` in BudgetPLCollection.js
- Split publication method by roles in BudgetPLCollection.js
- Refactor to reduce duplication in Footer.jsx
