### ISSUE TITLE
Review 9: ImportSheet.jsx and ManageProjections.jsx

### ISSUE THREAD

**Issue by PaytonHAH** [Team-Half-and-Half/spirebooks#152]
## Overview 
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-9

## Files to review

* [ImportSheet.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-9/app/imports/ui/pages/ImportSheet.jsx)
* [ManageProjections.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-9/app/imports/ui/pages/ManageProjections.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 11/11/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by caspascual** [comment]
ImportSheet.jsx

L31-33: Design-09: Move into separate file in utilities for data processing

L35-53: Design-09: Move into separate file in utilities for data processing

L58-79: Design-09: Move into separate file in utilities for data processing

L81-240: Design-09: Move into separate file in utilities for data processing

L242-267: Design-09: Move into separate file in utilities for file processing

L269-272: Design-09: Move into separate file in utilities for file processing

L273-276: Design-09: Move into separate file in utilities for file processing

L280-286: Design-09: Move into separate file in utilities for file processing

JS-01: Rename unnecessaryDataRemoved to something that is not unnecessarily long

JS-07: Remove all console logs

ManageProjections.jsx

L35-40: Design-09: Move into separate file in utilities for file processing

L42-67: Design-09: Move into separate file in utilities for file processing

L69-86: Design-09: Move into separate file in utilities for file processing

L30-31: Can remove, data and setData is used for showing the uploaded data in ImportSheet.jsx using react-spreadsheet

**Comment by beydlern** [comment]
**ImportSheet.jsx**

- L5: Wildcard import should be reassessed to see if you're using everything from `xlsx`.

- The `console.log()` statements should be commented or removed.

**ManageProjections.jsx**

- L149-155: "Loading" text can be used as input inside the `LoadingSpinner` component using the input `message` (e.g. \<LoadingSpinner message="Loading" />).

**Comment by samallari** [comment]
ImportSheet.jsx
- L87-235: Is there a way to refactor unnecessaryDataRemoved to avoid hard coding it for each category and index? Like using a for loop?

ManageProjections.jsx
- L30-31: data and setData was copied over from ImportSheet.jsx, can remove and this will fix eslint error

**Comment by bksnelson** [comment]
ImportSheet.jsx
JS-07 avoid using console log.
React-01 can be used as component.
ManageProjections.jsx
JS-07 avoid using console log.

**Comment by PaytonHAH** [comment]
### ImportSheet.jsx
_JS-07:_ _Avoid_ _console.logs_
  Lines:  89, 99, 100, 117, 118, 135, 136, 150, 151, 164, 165, 
             179, 180, 188, 189, 206, 207, 228, 229, 238, 239
### ManageProjections.jsx
_ESLINT-01: No errors, avoid warnings._
  Disabling of ESlint should be avoided
