### ISSUE TITLE
Order #39: Setup whatever we're doing for "sign up"

### ISSUE THREAD

**Issue by XavierBurt** [Team-Half-and-Half/spirebooks#49]
Either

A. Let users sign up, but make them go through a verification process with a Spire employee

B. Restrict users from signing up, let a spire employee make their account for them and give it to them

C. Leave it as is now, let users sign up and input data whenever they want.

**Comment by beydlern** [comment]
I will choose option A for my implementation of this issue. Users will be assigned a new Boolean value `verified` in their data when their account is made that will determine if they can see all of the interactable user pages (submitting data and seeing data), the page elements will be replaced with a type of message informing the user that they haven't been verified by a Spire employee to view these pages if the Boolean value `verified` is set to false. The default user account will have its value set to true for `verified`. Another page for admins/employees/accountants will be available where a list of users with a button to toggle their verification will be implemented.
