### ISSUE TITLE
Review 2: ImportSheet.jsx and Landing.jsx 

### ISSUE THREAD

**Issue by beydlern** [Team-Half-and-Half/spirebooks#68]
## Overview

Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-2](https://github.com/Team-Half-and-Half/spirebooks/tree/review-2)

## Files to review

* [ImportSheet.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/main/app/imports/ui/pages/ImportSheet.jsx)
* [Landing.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/main/app/imports/ui/pages/Landing.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 9/23/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by t-tirabassi** [comment]
ImportSheet.jsx:

Design-07: Minor comments could be added to explain lines 15 and 29 to ensure readability

React-01: The file upload on line 34 and the data display on lines 35-40 could be made into smaller components that way they can be isolated and imported into the ImportSheet page

Landing.jsx:

Design-07: The different sections could be split up into subcomponents for better organization

JS-04: Some of the repeating classNames could be condensed into a CSS class

**Comment by caspascual** [comment]
ImportSheet.jsx

L1-47: Design-05: Comments should be added to describe how the code works

L10-15,17-32: Design-09: These functions could be made into their own components for reusability

Landing.jsx

L6-48: Design-07: Empty new lines could be added in between each component for better readability so we can tell which part is which

L6-48: Design-05: Could add some comments to indicate which part is which (ex. logo, middle page, etc.)

**Comment by beydlern** [comment]
**ImportSheet.jsx**

DESIGN-07: Code should be readable, comments on arrow function sections (i.e. L10 and L17) would bolster readability

L2: Importing every function from xlsx may be inefficient

**Landing.jsx**

DESIGN-01: Refactor duplicated classNames styling into a CSS class or id

**Comment by bksnelson** [comment]
ImportSheet.jsx
JS-01: newTDAta L11. newTData. 
DS-05: Could use some comments on the sections of code and about how it works. 
DS-09: Could be its own component instead of page. We might need import functionality on multiple pages. 

Should have some error handling and successful import notifications with sweetalert. 

Landing.jsx
DS-05: Could use a comment just to say it's a landing page. 

Might need some column sizing adjustments and breakpoints. xs - lg. Currently, third row doesn’t stack on smaller browser sizes.

**Comment by PaytonHAH** [comment]
Landing.jsx
  Design-05 - Additional comments to explain some certain parts of the component
              in case of modification.

ImportSheet.jsx
  Design-05 - Additional comments would help in explaining how importing works,
              in case modification is required.
  Use of Wildcard imports for xlsx, only import what is required.

**Comment by samallari** [comment]
ImportSheet.jsx
- L36: should add more description here for the user about what to import, what are acceptable files, what happens after you import, etc.

Landing.jsx
- lots of nesting, can improve the readability of code by adding space between the rows/components

**Comment by XavierBurt** [comment]
ImportSheet.jsx

The functions could be made to be components in their own file

Landing.jsx

Maybe add some comments telling what does what

**Comment by samallari** [comment]
### Overview of Review Meeting
New issues:
- add error/successful import notifications in ImportSheet.jsx
- add responsiveness to Landing.jsx
