### ISSUE TITLE
Order #8: Design Data Visualization page

### ISSUE THREAD

**Issue by XavierBurt** [Team-Half-and-Half/spirebooks#7]
Please do work for this task in a branch called issue-7.

- Design page that accurately visualizes the data
- Easy for new users to understand
- Visually pleasing

**Comment by samallari** [comment]
Completed in [issue-97](https://github.com/orgs/Team-Half-and-Half/projects/6?pane=issue&itemId=82488624&issue=Team-Half-and-Half%7Cspirebooks%7C97).
