### ISSUE TITLE
Review 4: ManageDatabase.jsx and VerificationTable.jsx

### ISSUE THREAD

**Issue by beydlern** [Team-Half-and-Half/spirebooks#94]
## Overview

Please pay attention too:
* JavaScript issues
* React components

## Review Branch

[review-4](https://github.com/Team-Half-and-Half/spirebooks/tree/review-4)

## Files to review

* [ManageDatabase.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-4/app/imports/ui/pages/ManageDatabase.jsx)
* [VerificationTable.jsx](https://github.com/Team-Half-and-Half/spirebooks/blob/review-4/app/imports/ui/pages/VerificationTable.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/main/checklists/react-checklist.md)

## Due date

Monday, 10/7/2024

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by t-tirabassi** [comment]
**ManageDatabase.jsx:**

JS-04: Lines 16-22 could use deconstruction where result in the .then block could instead be timestamp. This way result.timestamp on Line 19 could be changed to just timestamp.

REACT-01: On line 26, the Dump Database button could be made into a separate component only if Manage Database is planning to be expanded upon later on.

**VerificationTable.jsx:**

REACT-06: On line 11, withTracker should be used instead of useTracker.

**Comment by caspascual** [comment]
ManageDatabase.jsx

L11: Design-09: databaseFileDateFormat could be placed into a constants file in utilities or just in settings.development.json

VerificationTable.jsx

L21-23: JS-05: Use arrow function

**Comment by beydlern** [comment]
**ManageDatabase.jsx**

DESIGN-05: L14-L21: Succinct comments describing what is happening during the saving file process.

L25-27: Components should be implemented in its own component file and imported into a page to use.

**VerificationTable.jsx**

L21-23: Meteor.call() function should include a way to handle errors. If the method throws an error, the first argument in the callback is the error. Meteor.call() functions return two arguments, the error and the result.

**Comment by bksnelson** [comment]
VerificationTable.jsx
JS-04: User can be destructured. L40
Could use comments.
If table becomes bigger, might need to adjust column sizing. md{7}.

ManageDatabase.jsx
Could use comments.
Might be good to separate as a component if more things are added to the page.

**Comment by XavierBurt** [comment]
**ManageDatabase.jsx**

Maybe a couple comments 
Line 26: Always specify the type attribute for a <button> element, to tell browsers what type of button it is.

**VerificationTable.jsx**

Line 46: Always specify the type attribute for a <button> element, to tell browsers what type of button it is.

**Comment by PaytonHAH** [comment]
ManageDatabase.jsx
Design-07: Ensure code is readable:
Some additional comments to ensure readability incase we need to further modify this file. 

VerificationTable.jsx
JS-05: Use arrow functions when appropriate: 
Function verifyButton(user) can be an arrow function.

**Comment by samallari** [comment]
ManageDatabase.jsx
- what is zip = new ZipZap() ? add comments for readability
- display instructions to the webpage about what it is about and what it is used for

VerificationTable.jsx
- maybe have a way to delete users if necessary?

**Comment by jsapolu99** [comment]
VerificationTable.jsx:

REACT-06: L11: withTracker should be used instead of useTracker.

ManageDatabase.jsx

DESIGN-05: L14-L21: Add concise comments explaining the file-saving process.
